T2C/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CC.Core.Mapping;
using CellService;
using Domain.T2C;
using Domain.T2C.Interface;
using T2C.Login;
using T2C.Models;

namespace T2C.Controllers
{
    [AllowAnonymous]
    public class PageController : Controller
    {
        private readonly IService _servicio;
        private readonly IMapper _mapper;

        public PageController(IService servicio, IMapper mapper)
        {
            _servicio = servicio;
            _mapper = mapper;
        }

        //Listar las compañia

        //Si marco una compañia, cargar lmarcas de esa compaña y mostrar los equpos
        //Cuando cargo la marca y la compañia mostrar los equipos de estas dopciones 



        public JsonResult ListCompanAndMarca(string name)
        {
            var list = _servicio.GetImagesNameType(name);
            return Json(list, JsonRequestBehavior.AllowGet);

        }

        public JsonResult ListImageToType(string tipo)
        {
            var list = _servicio.GetImagesType(tipo);
            return Json(list, JsonRequestBehavior.AllowGet);
           
        }

        public JsonResult ListAllDivice()
        {
            var list = _servicio.GetAll();
            return Json(list, JsonRequestBehavior.AllowGet);

        }

        public JsonResult ListComputers(string size, string processor, int year, string model, string category)
        {
            
            var list = _servicio.FilterComputers( Convert.ToDouble(size),  processor,  year,  model,  category);
            foreach (var t in list)
            {
                t.Imagens = LoadImagesCell(t.Id);
                if (!t.Imagens.Any())
                {
                    var pathImage = "/Resources/notImage.jpg";
                    t.Imagens = new List<IImagen>()
                    {
                        new Imagen()
                        {
                            PathImagen = pathImage
                        }
                    };
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);

        }

        public JsonResult FilterDivice(string name, string model, string company, string condition, int price,
            int memory, string category, string type, string generation)
        {
            var list = _servicio.ListCEll(name, model, company, condition, price, memory, category, type, generation);
            foreach (var t in list)
            {
                t.Imagens = LoadImagesCell(t.Id);
                if (!t.Imagens.Any())
                {
                    var pathImage = "/Resources/notImage.jpg";
                    t.Imagens = new List<IImagen>()
                    {
                        new Imagen()
                        {
                            PathImagen = pathImage
                        }
                    };
                }
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        public void ListAttributeCell(IEnumerable<CellModel> list)
        {
            var listModel = new List<ListItem>();
            var a = new ListItem() {Text = "Modelo", Value = string.Empty};
            listModel.Add(a);
            var listMemory = new List<ListItem>();
            a = new ListItem() {Text = "Capacidad", Value = "0"};
            listMemory.Add(a);
            var listCompany = new List<ListItem>();
            a = new ListItem() {Text = "Compania", Value = string.Empty};
            listCompany.Add(a);
            foreach (var cell in list)
            {
                var lista = new ListItem() {Text = cell.Model, Value = cell.Model};
                listModel.Add(lista);
                lista = new ListItem() {Text = cell.Memory.ToString(), Value = cell.Memory.ToString()};
                listMemory.Add(lista);
                lista = new ListItem() {Text = cell.Company, Value = cell.Company};
                listCompany.Add(lista);
            }

            ViewBag.Model = listModel;
            ViewBag.Memory = listMemory;
            ViewBag.Company = listCompany;
        }

        public void ListSelect()
        {
            // list.AddRange(from object state in Enum.GetValues(typeof(State)) select new ListItem() { Text = Enum.ToObject(typeof(State), state).ToString(), Value = Enum.ToObject(typeof(State), state).ToString() });
            //ViewBag.Activate = list;

            var listCondition = new List<ListItem>()
            {
                new ListItem() {Text = @"Condicion", Value = string.Empty},
                new ListItem() {Text = @"Bueno", Value = "Bueno"},
                new ListItem() {Text = @"Regular", Value = "Regular"},
                new ListItem() {Text = @"Malo", Value = "Malo"}
            };

            var listPrice = new List<ListItem>()
            {
                new ListItem() {Text = @"Precio", Value = "0"},
                new ListItem() {Text = @"$10 - $20", Value = "1"},
                new ListItem() {Text = @"$20 - 100", Value = "2"},
                new ListItem() {Text = @"$100 - $300", Value = "3"},
                new ListItem() {Text = @"$300 - más", Value = "4"}
            };


            ViewBag.Price = listPrice;
            ViewBag.Condition = listCondition;
        }

        private IEnumerable<IImagen> LoadImagesCell(Guid IdidEquipo)
        {
            return _servicio.GetImagesNameType("Equipo").Where(c => c.IdEquipo == IdidEquipo).ToList();


        }
       
        private void Visit(IEnumerable<CellModel> list)
        {
            list = list.OrderBy(e => e.Price).Take(8).ToList();
            var cellModels = list.ToArray();

            for (int i = 0; i < cellModels.Count(); i++)
            {
                cellModels[i].Imagens = LoadImagesCell(cellModels[i].Id);
            }
            ViewBag.Visits = list;
        }

        public ActionResult t2c()
        {
            return View();
        }

        public ActionResult Iphone()
        {
            return View(); 
        }
        public ActionResult Tablet()
        {
            return View();
        }
        public ActionResult Android()
        {
            return View();
        }
        public ActionResult Ipad()
        {
            return View();
        }
        public ActionResult Ipod()
        {
            return View();
        }
        public ActionResult Computers()
        {
            return View();
        }
        public ActionResult DetailsIpod(Guid id)
        {
            var cell = _servicio.GetCell(id);
            cell.Imagens = LoadImagesCell(cell.Id);
            return View(_mapper.Map<CellModel>(cell));
        }
        public ActionResult DetailsIpad(Guid id)
        {
            var cell = _servicio.GetCell(id);
            cell.Imagens = LoadImagesCell(cell.Id);
            return View(_mapper.Map<CellModel>(cell));
        }
        public ActionResult DetailsComputers(Guid id)
        {
            var cell = _servicio.GetCell(id);
            cell.Imagens = LoadImagesCell(cell.Id);
            return View(_mapper.Map<CellModel>(cell));
        }

        // GET: Cell
        public ActionResult Index()
        {
            ListSelect();
         
            var list = _mapper.Map<IEnumerable<CellModel>>(_servicio.GetAll());
            ListAttributeCell(list);
            Visit(list);
            return View(list);
        }
       
        [HttpPost]
        public ActionResult Index(string name, string model, string company, string condition,  int price, int memory,string category,string type,string generation)
        {
            ListSelect();
       
            var list = _mapper.Map<IEnumerable<CellModel>>(_servicio.GetAll());
            ListAttributeCell(list);
            Visit(list);
            var a = _mapper.Map<IEnumerable<CellModel>>(_servicio.ListCEll(name, model, company, condition, price, memory, category, type, generation));

            return View(a);
        }

        
        public ICell AddVisit(Guid id)
        {

            var cell = _servicio.GetCell(id);
            if (cell != null)
            {
                cell.Visits++;
                _servicio.UpdateCell(cell,"");

            }
            return cell;
        }
        public ActionResult Details(Guid id)
        
        {
            ListSelect(); 
         
            var list = _mapper.Map<IEnumerable<CellModel>>(_servicio.GetAll());
            ListAttributeCell(list);
            Visit(list);
            var cell = AddVisit(id);
            cell.Imagens = LoadImagesCell(cell.Id);
            return View(_mapper.Map<CellModel>(cell));
        }

       
      
       
    }
}

T2C/Views/Page/Android.cshtml
@{
    ViewBag.Title = "Android";
    Layout = "~/Views/Shared/_MainPage.cshtml";
}

<div class="container" ng-controller="AngularCtrl" ng-init="listImagenesMarca('Phone')">
    <div class="row col-md-offset-1" style="margin-top: 20px">
        <h3>Sell your iPhone for cash</h3>
        <h4>It takes just a few minutes to sell your iPhone.</h4>
    </div>
    <div class="main_content">
        <div id="stacks_content" class="iphone" style="height: auto;">
            <div class="row set">
          
                    <ul style="padding-left: 110px;" class="main_stack carrier_stack level_1 container">
                        <li class="line-select" style="height: auto; opacity: 1">
                            <a href="~/Page/Iphone" ng-show="divSelectModelo" style="height: auto; opacity: 1;" ng-model=" nametype"><img class="img" src="~/Resources/Apple.png" alt="properties" height="120" width="70"></a>
                            <a href="~/Page/Iphone" ng-show="divSelectModeloImage" style="height: auto; opacity: 1;" class="col-md-12">Apple</a>
                        </li>
                        <li class="line-select" ng-repeat="category in imagenesListFromType" style="height: auto; opacity: 1" ng-class="{act: $index==isActivateModelo}" ng-click="selectActivateModelo($index)">
                            <a ng-show="divSelectModelo" style="height: auto; opacity: 1;" ng-model=" nametype"><img class="img" src="{{category.PathImagen}}" ng-click="ClicGetkDivices('','','','', '0','0',category.NameType,'Phone','',1)" alt="properties"></a>
                            <a ng-show="divSelectModeloImage" style="height: auto; opacity: 1;" ng-click="ClicGetkDivices('','','','', '0','0',category.NameType,'Phone','',1)" class="col-md-12">{{category.NameType}}</a>
                        </li>
                    </ul>
            </div>

            <div class="row set">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <ul style="padding-left: 110px;" class="main_stack carrier_stack level_1 container">
                        <li class="line-select " ng-repeat=" company in ListCompany" style="height: auto; opacity: 1" ng-class="{act: $index==isActivate}"
                            ng-click="selectActivate($index,company.NameType)">
                            <a href="" ng-show="divSelectCompania" style="height: auto; opacity: 1;" ng-model="NameType"> <img src="{{company.PathImagen}} " ng-click="ClicGetkDivices('','',company.NameType, '' ,'0','0',Category,'Phone','',5)" alt=" properties" height="70" width="90"></a>
                            <a heref="" ng-show="divSelectCompaniaImage" style="height: auto; opacity: 1;" class="col-md-12" ng-model="Company" ng-click="ClicGetkDivices('','',company.NameType, '' ,'0','0',Category,'Phone','',5)">{{company.NameType}}</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>


    </div>

    <br />

    <div class="clearfix"></div>

    <h4 class="row text-center" ng-show="divSelectPhone" style="background-color: sienna; color: aliceblue">
        Select your <label style="color: black"> {{Category}}   {{Company}}  </label>  to sell.

    </h4>


    <div class="properties-listing spacer" ng-show="divSelectPhone" style="margin-left: -10px">
        <div class="col-lg-3 col-sm-3 table-bordered" ng-repeat="divice in getlistDivice ">
            <h5 align="center">
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target=" _self">{{divice.Name}}  </a>
            </h5>
            <div class="properties">
                <div class="image-holder">
                    @*img-responsive*@
                    <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target="_self">
                        <img class="img" src="{{divice.Imagens[0].PathImagen}}" class="" alt="properties" height="220" width="170">
                    </a>
                    <div class="status sold">
                        Estado: {{divice.Condition}}
                    </div>
                </div>
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target="_self">
                    {{divice.Model}}
                </a>
                <p class="price">
                    <h3 class="text-danger">Precio: ${{divice.Price}}</h3>
                </p>
                <div class="listing-detail">
                    <span class="glyphicon glyphicon-copyright-mark" data-toggle="tooltip" data-placement="bottom" title="Marca:{{divice.Category}} "></span>
                    <span class="glyphicon glyphicon-floppy-disk" data-toggle="tooltip" data-placement="bottom" title="Memoria:{{divice.Memory}}GB"></span>
                    <span class="glyphicon  glyphicon-barcode" data-toggle="tooltip" data-placement="bottom" title="Modelo:{{divice.Model}}"></span>
                </div>
            </div>

        </div>

    </div>




</div>

T2C/Views/Page/Computers.cshtml
@{
    ViewBag.Title = "Computers";
    Layout = "~/Views/Shared/_MainPage.cshtml";
}

<div class="container" ng-controller="AngularCtrl" ng-init="listImagenesMarca('Computers')">
    <div class="row col-md-offset-1" style="margin-top: 20px">
        <h3>Sell your iPhone for cash</h3>
        <h4>It takes just a few minutes to sell your iPhone.</h4>
    </div>
    <div class="main_content">
        <div id="stacks_content" class="iphone" style="height: auto;">
            <div class="row set">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <ul style="padding-left: 110px;" class="main_stack carrier_stack level_1 container">
                        <li class="line-select" ng-repeat="category in imagenesListFromType" style="height: auto; opacity: 1" ng-class="{act: $index==isActivateModelo}" ng-click="selectActivateModelo($index)">
                            <a ng-show="divSelectModelo" style="height: auto; opacity: 1;" ng-model=" nametype"><img class="img" src="{{category.PathImagen}}" ng-click="ClicGetkDivices('','','','', '0','0',category.NameType,'Computers','',3)" alt="properties"></a>
                            <a ng-show="divSelectModeloImage" style="height: auto; opacity: 1;" ng-click="ClicGetkDivices('','','','', '0','0',category.NameType,'Computers','',1)" class="col-md-12">{{category.NameType}}</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-2"></div>
            </div>


            <div class="row set">
                <div class="col-md-2"></div>
                <div class="col-md-8" ng-show="divSelectModeloImage">
                    <ul style="padding-left: 110px; padding-top: 20px;" class="main_stack carrier_stack level_1">
                        <li class="line-select" ng-repeat="modelo in modelos" style="height: auto; opacity: 1" ng-class="{act: $index==isActivateModelo}" ng-click="selectActivateModelo($index)">
                            <a ng-show="divSelectModelo" style="height: auto; opacity: 1;" ng-model=" nametype"><img src="{{modelo.Imagens[0].PathImagen}}" ng-click="LisComputer(0, '', 0, modelo.Model, Category, 1)" alt="properties" height="70" width="70"></a>
                            <a ng-show="divSelectModeloImage" style="height: auto; opacity: 1;" ng-click="LisComputer(0, '', '', modelo.Model, Category, 1)" class="col-md-12">{{modelo.Model}}</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-2"></div>
            </div>
            <br/>

            <div class="row set">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                   
                        @*//Si tiene Scrizie lo muestro *@
                    <div class="col-md-3" ng-show="selectDivSize" style="margin-top: 15px;"><label>Screen Size</label></div>
                    <select class="form-control col-md-5" style="margin-top: 15px;" ng-show="selectDivSize" ng-model="SpecificationsSize" ng-click="LisComputer(SpecificationsSize, '', 0, Model, Category, 2)">
                        <option ng-repeat="size in sizeComputersList" value={{size}}>
                            {{size}}
                        </option>
                    </select>

                    <div class="col-md-3" ng-show="selectDivProcessor" style="margin-top: 15px;"><label>Processor</label></div>
                    <select class="form-control col-md-5" style="margin-top: 15px;" ng-show="selectDivProcessor" ng-model="SpecificationsProcessor" ng-click="LisComputer(Size, SpecificationsProcessor, 0, Model, Category, 3)">
                        <option ng-repeat="processor in processorComputersList" value={{processor}}>
                            {{processor}}
                        </option>
                    </select>

                    <div class="col-md-3" ng-show="selectDivYear" style="margin-top: 15px;"><label>Year</label></div>
                    <select class="form-control col-md-5" style="margin-top: 15px;" ng-show="selectDivYear" ng-model="SpecificationsYear" ng-click="LisComputer(Size, Processor, SpecificationsYear, Model, Category, 4)">
                        <option ng-repeat="year in yearComputersList" value={{year}}>
                            {{year}}
                        </option>
                    </select>
                    <div class="button btn-danger col-md-1" style="margin-top: 15px;" ng-show="selectDivBottonComputer" ng-click="LisComputer(Size, Processor, Year, Model, Category, 5)">Next</div>
                </div>


          
                <div class="col-md-5" ng-show="selectDivSize">
                    <div id="help_floater" class="fade-in left" style="display: block; top: 384.292px; left: 425.764px;">
                        <h3> How to find your system specifications </h3>
                        <div class="content">
                            <div class="section">
                                <h4> Step 1 </h4>
                                <p> Click the Apple button in the upper left corner and choose 'About this Mac.' </p>
                                <img src="~/Resources/laptop_help_step1_original.png" alt="laptop-help-step1">
                                <div class="clear"></div>
                            </div>
                            <div class="section">
                                <h4> Step 2 </h4>
                                <p> If you are running OS X Mavericks or earlier, click on 'More Info'. Otherwise skip to step 3.' </p>
                                <img src="~/Resources/laptop_help_step2_original.png" alt="laptop-help-step2">
                                <div class="clear"></div>
                            </div>
                            <div class="section">
                                <h4> Step 3 </h4>
                                <p> Here you will find details about your Macbook, including the screen size, processor type, and model year. </p>
                                <div class="multi-image-column">
                                    <img src="~/Resources/laptop_help_step3_original.png" style="float: right; margin-right: 15px;" alt="laptop-help-step3">
                                    <img src="~/Resources/laptop_help_step3_yosemite_original.png" width="215" style="float: right; margin-top: 10px; margin-right: 15px;" alt="computer-help-step23-yosemite">
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="section">
                                <h4> Step 4 </h4>
                                <p> Click 'System Report' for additional specifications such as model identifier. Click 'Storage' to find hard drive capacity (round up to the closest option.)</p>
                                <div class="multi-image-column">
                                    <img src="~/Resources/laptop_help_step4_original.png" alt="laptop-help-step4">
                                    <img src="~/Resources/desktop_help_step4_yosemite_original.png" width="215" alt="laptop-help-step4-yosemite">
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>

                    </div>

                </div>

               
            </div>

        </div>


    </div>

    <br />

    <div class="clearfix"></div>

    <h4 class="row text-center" ng-show="divSelectPhone" style="background-color: sienna; color: aliceblue">
        Select your <label style="color: black"> {{Category}}   {{Model}}  </label>  to sell.

    </h4>


    <div class="properties-listing spacer" ng-show="divSelectPhone" style="margin-left: -28px">
        <div class="col-lg-3 col-sm-3 table-bordered" ng-repeat="divice in getlistDivice ">
            <h5 align="center">
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target=" _self">{{divice.Model}}  </a>
            </h5>
            <div class="properties">
                <div class="image-holder">
                    @*img-responsive*@
                    <img class="img" src="{{divice.Imagens[0].PathImagen}}" class="" alt="properties" height="220" width="170">
                    <div class="status sold">
                        Estado: {{divice.Condition}}
                    </div>
                </div>
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target="_self">

                </a>
                <p class="price">
                    <h3 class="text-danger">Precio: ${{divice.Price}}</h3>
                </p>
                <div class="listing-detail">
                    <span class="glyphicon glyphicon-copyright-mark" data-toggle="tooltip" data-placement="bottom" title="Marca:{{divice.Category}} "></span>
                    <span class="glyphicon glyphicon-floppy-disk" data-toggle="tooltip" data-placement="bottom" title="Memoria:{{divice.Memory}}GB"></span>
                    <span class="glyphicon  glyphicon-barcode" data-toggle="tooltip" data-placement="bottom" title="Modelo:{{divice.Model}}"></span>
                </div>
            </div>

        </div>

    </div>




</div>

T2C/Views/Page/Index.cshtml
@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_MainPage.cshtml";
}









@*//-----------------------------------------------------------------------------------------------------------------------*@



<div class="container" ng-controller="AngularCtrl">
    <div class="main_content">
        <div id="stacks_content" class="iphone" style="height: auto; ">
            <h4 class="col-md-offset-1 top"> Venda su equipo por dinero en efectivo </h4>
            <h6 class="col-md-offset-1">Se tarda sólo unos minutos para vender su equipo</h6>
            <div class="row set">
                <ul style="padding-left: 110px; " class="main_stack carrier_stack level_1 container">
                    <li class="line-select " ng-repeat=" company in ListCompany" style="height: auto; opacity: 1" ng-class="{act: $index==isActivate}"
                        ng-click="selectActivate($index,company.NameType)">
                        <a href="" ng-show="divSelectCompania" style="height: auto; opacity: 1;" ng-model="NameType"> <img class="img"src="{{company.PathImagen}} " ng-click="ClicGetkDivices('','',company.NameType, '' ,'0','0','',2)" alt=" properties" height="70" width="90"></a>
                        <a heref="" ng-show="divSelectCompaniaImage" style="height: auto; opacity: 1;" class="col-md-12" ng-model="Company" ng-click="ClicGetkDivices('','',company.NameType, '','0','0','',2)">{{company.NameType}}</a>
                    </li>
                </ul>

            </div>

            <div class="row set">
                <br ng-show="divSelectMarca" />
                <h3 ng-show="divSelectMarca" class="col-md-offset-1 product_headline">Selecciona tu equipo de {{nombreCompania}} para vender</h3>
                <ul style="padding-left: 110px; padding-top: 20px;" class="main_stack carrier_stack level_2">
                    <li class="line-select" ng-repeat="marca in ListMarcas" style="height: auto; opacity: 1;" ng-class="{act: $index==isActivateMarca}" ng-click="selectActivateMarca($index)">
                        <a ng-show="divSelectMarca" style="height: auto; opacity: 1;" ng-model=" nametype"><img class="img"src="{{marca.PathImagen}}" ng-click="ClicGetkDivices('','',company.NameType, '','0','0',marca.NameType,3)" alt="properties" height="70" width="70"></a>
                        <a ng-show="divSelectMarcaImage" style="height: auto; opacity: 1;" ng-click="ClicGetkDivices('','',company.NameType, '','0','0',marca.NameType,3)" class="col-md-12">{{marca.NameType}}</a>
                    </li>
                </ul>

            </div>

            <div class="row set">
                <ul style="padding-left: 110px; padding-top: 20px; " class="main_stack carrier_stack level_1">
                    <li class="line-select" ng-repeat="modelo in modelos" style="height: auto; opacity: 1"  ng-class="{act: $index==isActivateModelo}" ng-click="selectActivateModelo($index)">
                        <a ng-show="divSelectModelo" style="height: auto; opacity: 1;" ng-model=" nametype"><img class="img"class="img"src="{{modelo.Imagens[0].PathImagen}}" ng-click="ClicGetkDivices('',modelo.Model,company.NameType, '','0','0',marca.NameType,4)" alt="properties" height="70" width="70"></a>
                        <a ng-show="divSelectModeloImage" style="height: auto; opacity: 1;" ng-click="ClicGetkDivices('',modelo.Model,company.NameType, '','0','0',marca.NameType,4)" class="col-md-12">{{modelo.Model}}</a>
                    </li>
                </ul>

            </div>

            <div ng-show="divSelectMemory" style=" padding-top: 20px; opacity: 1">
    
                <div class="col-md-1 col-md-offset-1" ng-repeat="cap in Capacidad">
                    <input type="radio" name="capacidad" ng-click="ClicGetkDivices('',modelo.Model,company.NameType, '','0',cap,marca.NameType,5)" />{{cap}}GB
                </div>

            </div>
        </div>





    </div>




    <h4 class="row text-center" style="background-color: cornflowerblue; color: aliceblue">
        Busca el precio que pagamos por tus equipos en <label style="color: black">15 segundos.</label>
        <span class="glyphicon glyphicon-time"></span>
    </h4>

    <div class="properties-listing spacer">

        <div class="col-lg-3 col-sm-3 table-bordered" ng-repeat="divice in getlistDivice">

            <h5 align="center" style="margin-top: 10px">
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target=" _self">{{divice.Name}}  </a>
            </h5>
            <div class="properties">
                <div class="image-holder">
                    @*img-responsive*@
                    <img class="img"src="{{divice.Imagens[0].PathImagen}}" class="" alt="properties" height="220" width="170">
                    <div class="status sold">
                        Estado: {{divice.Condition}}
                    </div>
                </div>
                <a data-ng-href="@Url.Action("Details", "Page")/{{divice.Id}}" target="_self">
                    {{divice.Model}}
                </a>

                <p class="price">
                    <h3 class="text-danger">Precio: ${{divice.Price}}</h3>
                </p>
                <div class="listing-detail">
                    <span class="glyphicon glyphicon-copyright-mark" data-toggle="tooltip" data-placement="bottom" title="Marca:{{divice.Category}} "></span>
                    <span class="glyphicon glyphicon-floppy-disk" data-toggle="tooltip" data-placement="bottom" title="Memoria:{{divice.Memory}}GB"></span>
                    <span class="glyphicon  glyphicon-barcode" data-toggle="tooltip" data-placement="bottom" title="Modelo:{{divice.Model}}"></span>
                </div>

            </div>

        </div>

    </div>
    </div>




















    @*\
        @foreach (var item in Model)
        {

            <!-- properties -->
            <div class="col-lg-3 col-sm-3 table-bordered">

                <h5 align="center" style="margin-top: 10px">@Html.ActionLink(item.Name, "Details", new { id = item.Id }) </h5>
                <div class="properties">
                    <div class="image-holder">
                        <img src="~/Upload/Iphone.jpg" class="img-responsive" alt="properties">
                        <div class="status sold">Estado: @Html.DisplayFor(modelItem => item.Condition)</div>
                    </div>
                    <h4>@Html.ActionLink(item.Model, "Details", new { id = item.Id })</h4>
                    <p class="price">
                        Precio: $@Html.DisplayFor(modelItem => item.Price)
                    </p>

                    @{
            var enciende = "No";
            if (@item.Start)
            {
                enciende = "Si";
            }
                    }
                    <div class="listing-detail">
                        <span class="glyphicon glyphicon-barcode" data-toggle="tooltip" data-placement="bottom" data-original-title="Modelo: @Html.DisplayFor(modelItem => item.Model)"></span>
                        <span class="glyphicon glyphicon-floppy-disk" data-toggle="tooltip" data-placement="bottom" data-original-title="Memoria: @Html.DisplayFor(modelItem => item.Memory)GB"></span>
                        <span class="glyphicon glyphicon-sort" data-toggle="tooltip" data-placement="bottom" data-original-title="Enciende: @enciende"></span>

                    </div>
                    @Html.ActionLink("Ver", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                </div>

            </div>



        }*@








    <!-- properties -->
    @*<div class="center">
            <ul class="pagination">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">»</a></li>
            </ul>
        </div>*@

T2C/Views/Page/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>UploadFile</h2>

@{
    ViewBag.Title = "Multiple file upload with asp.net mvc and HTML5";
}

@*@using (Html.BeginForm("", "Page", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h3>Multiple file upload with asp.net MVCc/MVC3/MVC4/MVC5, C# and HTML5 </h3>
    <input type="file" name="files" value="" multiple="multiple" />
    <input type="submit" value="Upload You Image" title="Uplad" />
    <div style="color:Red;font-size:14px">@ViewBag.Message</div>
}*@