T2C/Controllers/ImagenController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CC.Core.Mapping;
using CellService;
using Domain.T2C;
using T2C.Login;
using T2C.Models;

namespace T2C.Controllers
{
[AllowAnonymous]
    public class ImagenController : Controller
    {
        private readonly IService _servicio;
        private readonly IMapper _mapper;

        public ImagenController(IService servicio, IMapper mapper)
        {
            _servicio = servicio;
            _mapper = mapper;
        }

      
        public void ListSelect()
        {
            // list.AddRange(from object state in Enum.GetValues(typeof(State)) select new ListItem() { Text = Enum.ToObject(typeof(State), state).ToString(), Value = Enum.ToObject(typeof(State), state).ToString() });
            //ViewBag.Activate = list;

            var listCategorias = new List<ListItem>()
            {
               
                 new ListItem() { Text = @"Compañía", Value = "Compañía"},
                  new ListItem() { Text = @"Marca", Value = "Marca"}
            };
            var listCondition = new List<ListItem>()
            {
                 new ListItem() { Text = @"Bueno", Value = "Bueno"},
                  new ListItem() { Text = @"Regular", Value = "Regular"},
                   new ListItem() { Text = @"Malo", Value = "Malo"}
            };


            ViewBag.ListCondition = listCondition;



            ViewBag.ListCategriaImagenes = listCategorias;

        }
        // GET: Imagen
        public ActionResult Index()
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            return View(_mapper.Map<IEnumerable<ImagenModel>>(_servicio.GetAllImagen()));
        }

        // GET: Imagen/Details/5
        public ActionResult Details(Guid id)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");

            return View(_mapper.Map<ImagenModel>(_servicio.GetImagen(id)));
        }

        // GET: Imagen/Create
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            ListSelect();
            
            return View();
        }

        // POST: Imagen/Create
        [HttpPost]
        public ActionResult Create(ImagenModel imagen, HttpPostedFileBase[] files,string category,string type)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            ListSelect();
            if (string.IsNullOrEmpty(category))
                return View();
            imagen.Category = category;
            imagen.Type = type;
            try
            {
                var filename = string.Empty;
                var filepathtosave = "/Resources/notImage.jpg";
                if (files != null && files.Any())
                {
                    foreach (HttpPostedFileBase file in files)
                    {
                        if (file != null)
                        {
                            filename = Path.GetFileName(file.FileName);
                            /*Saving the file in server folder*/
                            file.SaveAs(Server.MapPath("~/Upload/" + filename));
                            filepathtosave = "/Upload/" + filename;
                            /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                        }
                        /*Geting the file name*/

                    }

                }
                
                imagen.Name = filename;
                imagen.PathImagen = filepathtosave;
                _servicio.AddImagen(_mapper.Map<ImagenModel, Imagen>(imagen));

                ViewBag.Message = "La imagen subio satisfactoriamente";
                return RedirectToAction("Create");
            }
            catch(Exception m)
            {
                ViewBag.MessageData = m.Message;
            }
            return View();
        }




        // GET: Imagen/Edit/5
        public ActionResult Edit(Guid id)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            ListSelect();
          
            var imagen = _mapper.Map<ImagenModel>(_servicio.GetImagen(id));
            //ViewBag.NombreCategoria = new SelectList(_servicio.GetAgenciaAll(), "Nombre", "Nombre", agencia.Name);


            return View(imagen); 
        }

        // POST: Imagen/Edit/5
        [HttpPost]
        public ActionResult Edit(ImagenModel imagen, HttpPostedFileBase[] files)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            ListSelect();
           
            if (ModelState.IsValid)
            {

                if (files != null && files[0]!=null)
                {
                    var filename = string.Empty;
                    var filepathtosave = "/Resources/notImage.jpg";
                    foreach (HttpPostedFileBase file in files)
                    {
                        if (file != null)
                        {
                            filename = Path.GetFileName(file.FileName);
                            /*Saving the file in server folder*/
                            file.SaveAs(Server.MapPath("~/Upload/" + filename));
                            filepathtosave = "/Upload/" + filename;
                            /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                        }
                        /*Geting the file name*/

                    }
                    imagen.Name = filename;
                    imagen.PathImagen = filepathtosave;

                }

                var pathServer = Server.MapPath("~/Upload/");
                _servicio.UpdateImagen(_mapper.Map<Imagen>(imagen), pathServer);

                return RedirectToAction("Index");
            }

            return View(imagen);
        }

        // GET: Imagen/Delete/5
        public ActionResult Delete(Guid id)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            return View(_mapper.Map<ImagenModel>(_servicio.GetImagen(id)));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(Guid id)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            _servicio.RemoveImagen(_mapper.Map<Imagen>(_servicio.GetImagen(id)));
            return RedirectToAction("Index");
        }


        public ActionResult DeleteAllImagen()
        {
            try
            {
                _servicio.RemoveAllImages();
                return RedirectToAction("Index");
            }
            catch (Exception m)
            {

                return RedirectToAction("Index");
            }


        }



        //----------------------------------Prueba de metoos para guardar imagen----------


        public JsonResult UploadFiles(object obj)
        {
            try
            {
                var length = Request.ContentLength;
                var bytes = new byte[length];
                Request.InputStream.Read(bytes, 0, length);

                var fileName = Request.Headers["X-File-Name"];
                var fileSize = Request.Headers["X-File-Size"];
                var fileType = Request.Headers["X-File-Type"];

                var saveToFileLoc = Server.MapPath("~/Upload/" + fileName);

                // save the file.
                var fileStream = new FileStream(saveToFileLoc, FileMode.Create, FileAccess.ReadWrite);
                fileStream.Write(bytes, 0, length);
                fileStream.Close();

                return Json("Esxiste", JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                return Json("false", JsonRequestBehavior.AllowGet);
            }




            //return string.Format("{0} bytes uploaded", bytes.Length);
        }



        [HttpPost]
        public IList<string> UploadFile(HttpPostedFileBase[] files)
        {
            var list = new List<string>();
            try
            {
                /*Lopp for multiple files*/
                foreach (HttpPostedFileBase file in files)
                {
                    /*Geting the file name*/
                    string filename = Path.GetFileName(file.FileName);
                    /*Saving the file in server folder*/
                    file.SaveAs(Server.MapPath("~/Upload/" + filename));
                    string filepathtosave = "Upload/" + filename;
                    /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/
                    list.Add(filepathtosave);
                }
                return list;
            }
            catch
            {
                ViewBag.Message = "Error mientras subia la imagen.";
            }
            return null;
        }



        public ActionResult UploadImagenToServer(HttpPostedFileBase file)
        {
            try
            {
                /*Lopp for multiple files*/
                /*Geting the file name*/
                string filename = Path.GetFileName(file.FileName);
                /*Saving the file in server folder*/
                file.SaveAs(Server.MapPath("~/Upload/" + filename));
                string filepathtosave = "Upload/" + filename;
                /*HERE WILL BE YOUR CODE TO SAVE THE FILE DETAIL IN DATA BASE*/


                return Json("File Uploaded successfully.");
            }
            catch
            {
                return Json("Error while uploading the files.");
            }

        }
























        public ActionResult UploadFile()
        {

T2C/Views/Imagen/Create.cshtml
@model T2C.Models.ImagenModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}
@using (Html.BeginForm("Create", "Imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()



    <div class="form-horizontal" ng-controller="AngularCtrl">

        <hr />



        <div class="col-md-12 form-group">
            <h4>Imagen</h4>
            <div class="col-md-3">

                <div>
                    <div>
                        <div class="well my-drop-zone">
                            <img src="{{Path}}" style="width: 100%; height: 100%" />
                            Se visualizará la imagen cuando la seleccione
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="col-md-12" style="text-align: center; margin-bottom: 10px;">
                    <input type="file" name="files" value="" class="btn btn-warning " />
                    @* <input type="file" id="file" name="files" onchange="angular.element(this).scope().setFile(this)" accept="image/*" class="btn btn-warning"/>>*@
                </div>
                <div class="col-md-12 text-success" style="text-align: center; margin-bottom: 10px;">@ViewBag.Message</div>
            </div>

        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <select name="category" class="form-control" ng-model="selectedTypeDivice" ng-click="SelectCategoryImagen(selectedTypeDivice)">


                    @{
    var listaCategory = ViewBag.ListCategriaImagenes;
    foreach (var category in listaCategory)
    {
            <option value="@category">@category</option>
    }
                    }
                </select>


                @*@Html.DropDownListFor(model => model.Category, new SelectList(ViewBag.ListCategriaImagenes, "Value", "Text"), new { @class = "form-control" })*@

                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                <div class="col-md-10 text-danger">@ViewBag.MessageData</div>

            </div>
        </div>
        <div class="form-group" ng-show="selectDivTypeDivice" >
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="type" class="form-control"  ng-disabled="divDisableTypeDivice">
                    <option value="Iphone">Iphone</option>
                    <option value="Phone">Phone</option>
                    <option value="Ipad">Ipad</option>
                    <option value="Tablets">Tablets</option>
                    <option value="Ipod">Ipod</option>
                    <option value="Computers">Computers</option>
                    <option value="Other">Other</option> 
                </select>

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <input type="submit" value="Adicionar" class="btn btn-default">
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

T2C/Views/Imagen/Delete.cshtml
@model T2C.Models.ImagenModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}

<h3>Eliminar</h3>

<h4>¿Estás seguro(a) que desea eliminar el equipo?</h4>
<div class="row">
    <div class="col-md-5 col-lg-5">
        @{
            if (Model != null)
            {

                <img src=@Model.PathImagen class="img-responsive img-rounded" alt="properties" style="width: 100%; height: 100%;">

            }

        }

    </div>

    <div class="col-md-3">
        <hr />
        <dl class="dl-horizontal col-md-3 col-lg-3 col-md-pull-5">

            <dt>
                @Html.DisplayNameFor(model => model.NameType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameType)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>

        </dl>


    </div>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <button type="submit" class="btn btn-danger btn-s col-md-2">
        <span class="glyphicon glyphicon-trash"></span> Eliminar
    </button>
    <button type="submit" class="btn btn-warning btn-s col-md-2">
        <span class="glyphicon glyphicon-backward"></span> @Html.ActionLink("Volver", "Index")
    </button>
}

T2C/Views/Imagen/Details.cshtml
@model T2C.Models.ImagenModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}

<h2>Detalle</h2>

<div class="col-md-10">
    <div class="col-md-2">
        <div class="property-images imagen-center ">
            <img src=@Model.PathImagen width="100" height="100" />
        </div>
    </div>
    <div class="col-md-2 property-info">
        <div class="row">
            <strong>@Html.DisplayNameFor(model => model.NameType)</strong>
            @Html.DisplayFor(model => model.NameType)
        </div>
        <div class="row">
            <strong>
                @Html.DisplayNameFor(model => model.Type)</strong>
            @Html.DisplayFor(model => model.Type)
        </div>

    </div>


</div>
<div class="col-md-3">
    <p>
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Volver", "Index")
    </p>
</div>

T2C/Views/Imagen/Edit.cshtml
@model T2C.Models.ImagenModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}

<h3>Editar</h3>

@using (Html.BeginForm("Edit", "Imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" ng-controller="AngularCtrl">

        <hr />



        <div class="col-md-12 form-group">
            <h4>Imagen</h4>
            <div class="col-md-3">

                <div>
                    <div>
                        <div class="well my-drop-zone">
                            <img src="{{Path}}" style="width: 100%; height: 100%" />
                            Se visualizará la imagen cuando la seleccione
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="col-md-12" style="text-align: center; margin-bottom: 10px;">
                    <input type="file" name="files" value="" class="btn btn-warning " />
                    @* <input type="file" id="file" name="files" onchange="angular.element(this).scope().setFile(this)" accept="image/*" class="btn btn-warning"/>>*@
                </div>
                <div class="col-md-12 text-success" style="text-align: center; margin-bottom: 10px;">@ViewBag.Message</div>
            </div>

        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NameType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <select name="category" class="form-control" ng-model="selectedTypeDivice" ng-click="SelectCategoryImagen(selectedTypeDivice)">


                    @{
    var listaCategory = ViewBag.ListCategriaImagenes;
    foreach (var category in listaCategory)
    {
        <option value="@category">@category</option>
    }
                    }
                </select>


                @*@Html.DropDownListFor(model => model.Category, new SelectList(ViewBag.ListCategriaImagenes, "Value", "Text"), new { @class = "form-control" })*@

                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                <div class="col-md-10 text-danger">@ViewBag.MessageData</div>

            </div>
        </div>
        <div class="form-group" ng-show="selectDivTypeDivice">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="type" class="form-control" ng-disabled="divDisableTypeDivice">
                    <option value="Iphone">Iphone</option>
                    <option value="Phone">Phone</option>
                    <option value="Ipad">Ipad</option>
                    <option value="Tablets">Tablets</option>
                    <option value="Ipod">Ipod</option>
                    <option value="Computers">Computers</option>
                    <option value="Other">Other</option>
                </select>

            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <input type="submit" value="Adicionar" class="btn btn-default">
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

T2C/Views/Imagen/Index.cshtml
@model IEnumerable<T2C.Models.ImagenModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}



<h3>Datos</h3>

<div class="col-md-2 left ">@Html.ActionLink("Crear", "Create")</div>

<div class="col-md-2 right">@Html.ActionLink("Eliminar todo", "DeleteAllImagen")</div>


<table class="table table-bordered table-hove">
    <tr class="success" style="color: white">
        <th class="col-md-1">
            <label> Imagen</label>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="col-md-1">
                @{
        var path = item.PathImagen;
        if (!string.IsNullOrEmpty(path))
        {
            <img src=@item.PathImagen width="50" height="50" />
        }
        else
        {
            <img src="~/Resources/notImage.jpeg" width="50" height="50" />
        }

                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>


                <img src="~/Resources/Edit.png" alt="" height="15" width="15" />@Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                <img src="~/Resources/details.png" alt="" height="15" width="15" />@Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                <img src="~/Resources/Delete.png" alt="" height="15" width="15" /> @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })

            </td>
        </tr>
    }

</table>

T2C/Views/Imagen/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Administrator.cshtml";
}
<style>
    .my-drop-zone {
        border: dotted 3px lightgray;
    }

    .nv-file-over {
        border: dotted 3px red;
    }

    .another-file-over-class {
        border: dotted 3px green;
    }

    html, body {
        height: 100%;
    }
</style>





<div ng-controller="AppController" nv-file-drop="" uploader="uploader"
     filters="queueLimit, customFilter">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4>Ver Imagen</h4>
                <div >
                    <div>
                        <div class="well my-drop-zone">
                            Seleccionar la imagen de la tabla para ver visualizarla aquí
                        </div>
                    </div>
                </div>
                Single
                <input type="file" nv-file-select="" uploader="uploader"/>
            </div>




            <div class="col-md-8" style="margin-bottom: 40px">
                <h3>Lista de imágenes</h3>
              
                <table class="table">
                    <thead>
                        <tr>
                            <th width="50%">Nombre</th>
                            <th >Categoría</th>
                            <th >Tipo</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <tr >
                            <td><strong></strong></td>
                            <td  nowrap>
                               
                            </td>
                            <td >
                                <div class="progress" style="margin-bottom: 0;">
                                    <div class="progress-bar" role="progressbar"
                                         ng-style="{ 'width': item.progress + '%' }"></div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <div>
                        Queue progress:
                        <div class="progress" style="">
                            <div class="progress-bar" role="progressbar"
                                 ng-style="{ 'width': uploader.progress + '%' }"></div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-success btn-s col-md-2"
                            ng-click="uploader.uploadAll()"
                            ng-disabled="!uploader.getNotUploadedItems().length">
                        <span class="glyphicon glyphicon-upload"></span> Upload all
                    </button>
                    <button type="button" class="btn btn-warning btn-s col-md-2"
                            ng-click="uploader.cancelAll()" ng-disabled="!uploader.isUploading">
                        <span class="glyphicon glyphicon-ban-circle"></span> Cancel all
                    </button>
                    <button type="button" class="btn btn-danger btn-s col-md-2"
                            ng-click="uploader.clearQueue()" ng-disabled="!uploader.queue.length">
                        <span class="glyphicon glyphicon-trash"></span> Remove all
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>