T2C/Controllers/CellController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using CC.Core.Mapping;
using CellService;
using Domain.T2C;
using Domain.T2C.Interface;
using T2C.Login;
using T2C.Models;

namespace T2C.Controllers
{

    public class CellController : Controller
    {
        private readonly IService _servicio;
        private readonly IMapper _mapper;


        private bool GetList()
        {
            var listMarca = _servicio.GetImagesNameType("Marca");
            var listCompany = _servicio.GetImagesNameType("Compañía").ToList();

            //Cargar las marcas ya predefinidas cuando se vayan a crear o editar el equipo
            //var listMarcas = new List<ListItem>()
            //{
            //     new ListItem() { Text = @"Apple", Value = "Apple"},
            //      new ListItem() { Text = @"BlackBerry", Value = "BlackBerry"},
            //       new ListItem() { Text = @"HTC", Value = "HTC"},
            //       new ListItem() { Text = @"LG", Value = "LG"},
            //       new ListItem() { Text = @"Motorola", Value = "Motorola"},
            //       new ListItem() { Text = @"Nokia", Value = "Nokia"},
            //       new ListItem() { Text = @"Samsung", Value = "Samsung"}
            //};

            //var marcas = listMarca.Select(marca => new ListItem() { Text = marca.NameType, Value = marca.NameType }).ToList();
            //marcas.AddRange(listMarcas);
            //ViewBag.ListaMarcas = marcas;


            var listGeneration = new List<ListItem>()
            {
                 new ListItem() { Text = @"1RA GEN", Value = "1RA GEN"},
                  new ListItem() { Text = @"2DA GEN", Value = "2DA GEN"},
                   new ListItem() { Text = @"3RA GEN", Value = "3RA GEN"},
                   new ListItem() { Text = @"4TA GEN", Value = "4TA GEN"},
                   new ListItem() { Text = @"5TA GEN", Value = "5TA GEN"},
                   new ListItem() { Text = @"6TA GEN", Value = "6TA GEN"},
                   new ListItem() { Text = @"7MA GEN", Value = "7MA GEN"}
            };

            if (listMarca == null || listCompany == null) return false;



            var companias = listCompany.Select(company => new ListItem() { Text = company.NameType, Value = company.NameType }).ToList();

            var listCondition = new List<ListItem>()
            {
                 new ListItem() { Text = @"Bueno", Value = "Bueno"},
                  new ListItem() { Text = @"Regular", Value = "Regular"},
                   new ListItem() { Text = @"Malo", Value = "Malo"}
            };
            ViewBag.ListCompany = companias;
            ViewBag.Condition = listCondition;
            ViewBag.Generation = listGeneration;
            return true;
        }

        private void ListTypeDivice()
        {
            var listType = new List<ListItem>()
            {
                 new ListItem() { Text = @"Iphone", Value = "Iphone"},
                  new ListItem() { Text = @"Phone", Value = "Phone"},
                   new ListItem() { Text = @"Ipad", Value = "Ipad"},
                   new ListItem() { Text = @"Tablets", Value = "Tablets"},
                   new ListItem() { Text = @"Ipod", Value = "Ipod"},
                   new ListItem() { Text = @"Computers", Value = "Computers"},
                   new ListItem() { Text = @"Other", Value = "Other"}
            };
            ViewBag.ListType = listType;
        }

        private void ListDataComputers()
        {

            //Size
            var listSize = new List<ListItem>()
            {
                new ListItem() { Text = @"Screen Size", Value = ""},
                 new ListItem() { Text = @"11.6", Value = "11.6"},
                  new ListItem() { Text = @"13.3", Value = "13.,3"},
                   new ListItem() { Text = @"17", Value = "17"},
                   new ListItem() { Text = @"19", Value = "19"},
                   new ListItem() { Text = @"21", Value = "21"}
            };
            //Processor
            var listProcessor = new List<ListItem>()
            {
                new ListItem() { Text = @"Processor", Value = ""},
                  new ListItem() { Text = @"1.40 GHz", Value = "1.40 GHz"},
                  new ListItem() { Text = @"1.8 GHz", Value = "1.8 GHz"},
                  new ListItem() { Text = @"2.00 GHz", Value = "2.00 GHz"},
                  new ListItem() { Text = @"2.26 GHz", Value = "2.26 GHz"},
                  new ListItem() { Text = @"2.40 GHz", Value = "2.40 GHz"},
                  new ListItem() { Text = @"2.50 GHz", Value = "2.50 GHz"},
                  new ListItem() { Text = @"2.66 GHz", Value = "2.66 GHz"},
                  new ListItem() { Text = @"2.70 GHz", Value = "2.70 GHz"},
                  new ListItem() { Text = @"2.80 GHz", Value = "2.80 GHz"},
                  new ListItem() { Text = @"2.90 GHz", Value = "2.90 GHz"},
                  new ListItem() { Text = @"2.93 GHzz", Value = "2.93 GHz"},
                  new ListItem() { Text = @"3.06 GHz", Value = "3.06 GHz"},
                  new ListItem() { Text = @"3.10 GHz", Value = "3.10 GHz"},
                  new ListItem() { Text = @"3.20 GHz", Value = "3.20 GHz"},
                  new ListItem() { Text = @"3.33 GHz", Value = "3.33 GHz"},
                  new ListItem() { Text = @"3.4 GHz", Value = "3.4 GHz"},
                  new ListItem() { Text = @"3.40 GHz", Value = "3.40 GHz"},
                  new ListItem() { Text = @"3.50 GHz", Value = "3.50 GHz"},
                  new ListItem() { Text = @"3.60 GHz", Value = "3.60 GHz"},
                  new ListItem() { Text = @"4.00 GHz", Value = "4.00 GHz"}

            };
            //Year
            var listYear = new List<ListItem>()

            {new ListItem() { Text = @"Year", Value = ""},
                new ListItem() { Text = @"2007", Value = "2006"},
                 new ListItem() { Text = @"2007", Value = "2007"},
                  new ListItem() { Text = @"2008", Value = "2008"},
                   new ListItem() { Text = @"2009", Value = "2009"},
                   new ListItem() { Text = @"2010", Value = "2010"},
                   new ListItem() { Text = @"2011", Value = "2011"},
                   new ListItem() { Text = @"2011", Value = "2012"},
                   new ListItem() { Text = @"2011", Value = "2013"},
                   new ListItem() { Text = @"2011", Value = "2014"}
            };
            ViewBag.ListSize = listSize;
            ViewBag.ListProcessor = listProcessor;
            ViewBag.ListYear = listYear;
        }

        //public void ListModelo()
        //{
        //    //Modelos de Iphone ya predefinidos
        //    var listModelo = new List<ListItem>()
        //    {
        //         new ListItem() { Text = @"Iphone 6S Plus", Value = "Iphone 6S Plus"},
        //          new ListItem() { Text = @"Iphone 6S", Value = "Iphone 6S"},
        //           new ListItem() { Text = @"Iphone 6 Plus", Value = "Iphone 6 Plus"},
        //           new ListItem() { Text = @"Iphone 6", Value = "Iphone 6"},
        //           new ListItem() { Text = @"Iphone 5S", Value = "Iphone 5S"},
        //           new ListItem() { Text = @"Iphone 5C", Value = "Iphone 5C"},
        //           new ListItem() { Text = @"Iphone 5", Value = "Iphone 5"},
        //           new ListItem() { Text = @"Iphone 4S", Value = "Iphone 4S"}
        //    };

        //    ViewBag.ListaModelo = listModelo;
        //}

        public JsonResult ListMarca(string type)
        {
            return Json(_servicio.ListMarca(type), JsonRequestBehavior.AllowGet);

        }

        public JsonResult ListModel(string type, string category)
        {
            return Json(_servicio.ListModel(type, category), JsonRequestBehavior.AllowGet);

        }

        private IEnumerable<IImagen> LoadImagesCell(Guid idEquipo)
        {
            return _servicio.GetImagesNameType("Equipo").Where(c => c.IdEquipo == idEquipo).ToList();


        }

        public CellController(IService servicio, IMapper mapper)
        {
            _servicio = servicio;
            _mapper = mapper;
        }


        //Crear lista del estado del celular
        // GET: Cell

        public ActionResult Index()
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");

            var list = _servicio.GetAll().ToList();

            for (int i = 0; i < list.Count(); i++)
            {
                list[i].Imagens = LoadImagesCell(list[i].Id);
            }

            return View(_mapper.Map<IEnumerable<CellModel>>(list));
        }
        // GET: Cell/Details/5
        public ActionResult Details(Guid id)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            var cell = _servicio.GetCell(id);
            cell.Imagens = LoadImagesCell(cell.Id);
            return View(_mapper.Map<CellModel>(cell));
        }

        // GET: Cell/Create
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            //ListModelo();
            GetList();
            ListDataComputers();
            //ListTypeDivice();
            return View();
        }

        // POST: Cell/Create
        [HttpPost]
        public ActionResult Create(CellModel cell, HttpPostedFileBase[] files, string marca, string modelo, string tipo)
        {
            if (Session["UserID"] == null)
                return RedirectToAction("LoginUser", "User");
            //ListModelo();
            ListTypeDivice();
            ListDataComputers();
            if (!GetList()) return View(cell);
            if (!string.IsNullOrEmpty(modelo))
                cell.Model = modelo;
            if (string.IsNullOrEmpty(marca))

T2C/Views/Shared/_Administrator.cshtml
<!DOCTYPE html>
<html ng-app="MyApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - T2C</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body ng-controller="AngularCtrl">

    @* Barra de colores *@

    <div class="wrapper">
        <div class="bar-top headerSite"></div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-md-2">
                    <img src="~/Resources/Home.png" alt="" height="20" width="20" /> @Html.ActionLink("Visitar Sitio", "t2c", "Page")
                </div>
                <div class="col-md-2">
                    <img src="~/Resources/Electronic.png" alt="" height="15" width="15" /> @Html.ActionLink("Equipos", "Index", "Cell")
                </div>
                <div class="col-md-2 ">
                    <img src="~/Resources/imagen.png" alt="" height="20" width="20" /> @Html.ActionLink("Image", "Index", "Imagen")
                </div>
                <div class="col-md-2">
                    <img src="~/Resources/User-Profile.png" alt="" height="15" width="15" /> @Html.ActionLink("Usuario", "Index", "User")
                </div>

                <div class="col-md-3 pull-right">
                    @if (Session["UserID"] != null)
                    {
                        //Se visualiza cuando el usuario se encuentra autenticado en el sistema
                        <strong>@Session["Username"]</strong>
                        <img src="~/Resources/User-Login.png" alt="" height="20" width="20" />   @Html.ActionLink("Cerrar sesión", "LogOut", "User")
                    }

                </div>
            </div>

        </div>


        <div class="col-md-12">

            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - T2C</p>
            </footer>
        </div>
    </div>






    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Agenncia Turismo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Agencia", "index", "Agencia")</li>
                        <li>@Html.ActionLink("Categoria", "index", "Category")</li>

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@
    @Scripts.Render("~/angular/angular")
    @Scripts.Render("~/Scripts")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

T2C/Views/Shared/_ColumnRihgtPartial.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

T2C/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

T2C/Views/Shared/_MainPage.cshtml
<!DOCTYPE html>

<html ng-app="MyApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - T2C</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body ng-controller="AngularCtrl">

    <div class="wrapper">
        <div class="col-md-12 text-right">
            <img src="~/Resources/spanish.png" width="20" height="20" /><img src="~/Resources/english.png" width="20" height="20" />
        </div>
        <div class="col-md-12 headerSite"></div>
        <ul class="nav nav-pills" style="margin-top: 0; background-color: #f5deb3;font-family: brandon_grotesquelight;font-size: 15px;">
            <li><a href="~/Page/t2c">HOME</a></li>
             <li><a href="~/Page/Iphone">IPHONE</a></li>
            <li ><a href="~/Page/Android"> CELL PHONES</a></li>
            <li><a href="~/Page/Ipod">IPOD</a></li>
            <li><a href="~/Page/Ipad">IPAD</a></li>
            <li ><a href="~/Page/Tablet">TABLETS</a></li>
            <li><a href="~/Page/Computers">COMPUTERS</a></li>

        </ul>
        <div class="row">
            @RenderBody()
        </div>
        @*<div class="col-md-12">


                -----Propiedades mas vistas------
                <div class="col-md-12">
                    <div class="hot-properties hidden-xs">
                        <h4 class="row text-center" style="background-color: chocolate; color: aliceblue">
                            <span class=" glyphicon glyphicon-briefcase"></span> Mejores ofertas de la semana

                        </h4>

                        @{
                            var list = ViewBag.Visits;
                        }

                        <div class="row text-center" style="color: aliceblue; ">

                            @{
                                if (list != null)
                                {
                                    var count = 0;
                                    foreach (var item in list)
                                    {
                                        count ++;
                                        var imagen = "";
                                         var enumerable = item.Imagens as IList<IImagen> ?? item.Imagens.ToList();

                                         if (enumerable != null && enumerable.Count>0)
                                        {
                                            imagen = item.Imagens[0].PathImagen;
                                        }
                                        else
                                        {
                                            imagen = "/Resources/notImage.jpg";
                                        }
                            <div class="col-md-3">
                                <div class="col-md-5">
                                    <img src=@imagen class="img-responsive img-rounded" alt="properties">
                                </div>
                                <div class="col-md-3 col-lg-6 col-sm-5 text-left ">
                                    <h5>@item.Name</h5>
                                    <h3>
                                        <p class="price text-danger"> $@item.Price</p>
                                    </h3>
                                    <h5>
                                        <p class="price" style="margin-top: -10px;">@Html.ActionLink("Ver", "Details", "Page", new {id = item.Id}, new {@class = "text-center"})</p>
                                    </h5>
                                </div>
                            </div>
                                        if (count == 4)
                                        {


                                            count=0;

                                        }
                                    }
                                }
                            }
                            }

                        </div>
                    </div>
                </div>
            </div>*@

        <div class="row" style="margin-top: 20px;">
            <div class="row col-md-offset-1">
                <div class="col-md-3">
                    <h5 style="color: firebrick"><strong>What is T2C?</strong></h5>
                    T2C is an online reCommerce service that helps you sell your
                    used electronics for cash. Whether you are selling your iPhone, iPad or other smartphone,
                    T2C helps you get value for your old electronics.

                </div>

                <div class="col-md-4">
                    <h5 style="color: firebrick"><strong>What Happens When I Sell My Phone and Electronics?</strong></h5>
                    Once your trade in is received, your cell phones and electronics are inspected to make sure their
                    condition matches your evaluation. Then we send your payment. The process takes about a week once
                    we receive your box.

                </div>
                <div class="col-md-4">
                    <h5 style="color: firebrick"><strong>What Can I Sell to T2C?</strong></h5>
                    ou can sell your used iPhone, iPad, iPod or MacBook to T2C.  In addition to Apple products, we buy back smartphones from AT&T, Verizon, Sprint and other
                    major cell phone carriers.

                </div>
            </div>
        </div>
        <footer>
            <div class="footerCopy">
                <p>&copy; @DateTime.Now.Year - T2C, Inc. Todos los derechos reservados.</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/angular/angular")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>